import type { Pet } from './types';

/**
 * ============================================================
 *  PET-LISTA
 * ============================================================
 *
 * Ezt a fájlt a scripts/import-pets.mjs generálta a szerver wikijéről:
 * /tmp/claude-0/-home-user-j-tattoo/f6c41623-1bd0-5407-b5fd-d1a678651416/scratchpad/wiki-pets.html
 *
 * Kézzel is nyugodtan szerkeszthető. A wikin nincs megszerzési infó, ezért
 * minden petnél üres a `sources` – az oldal ezeket pirossal jelzi, és külön
 * rá lehet szűrni. Ahogy kiderül, honnan szerezhető meg egy pet, told ki a
 * `sources` tömböt és írd meg a `howToGet` mezőt:
 *
 *   sources: ['boss', 'trade'],
 *   howToGet: 'Az Árnyék Alfa bossból esik, cserélhető.',
 *   location: 'Sötét Erdő',
 *   bonuses: ['+6% támadóerő'],
 *
 * rarity  = 'common' | 'rare' | 'epic' | 'legendary'
 * sources = 'event' | 'shop' | 'drop' | 'boss' | 'dungeon'
 *         | 'quest' | 'craft' | 'trade' | 'donate' | 'other'
 *
 * FONTOS: az `id` mezőt utólag NE írd át! A látogatók pipái ez alapján
 * vannak elmentve, egy átnevezett id-nél elveszik a jelölés. Az importáló
 * szkript ezért a meglévő id-ket név alapján megtartja.
 */

/** Amíg true, az oldal tetején figyelmeztet, hogy ezek példaadatok. */
export const IS_SAMPLE_DATA = false;

export const PETS: Pet[] = [
  {
    id: 'azika',
    name: 'Azika',
    category: 'Pet kosztüm',
    rarity: 'common',
    sources: [],
    image: '/images/pets/azika.png',
    wikiUrl: 'https://wiki.venor2.hu/items/53005',
  },
  {
    id: 'azi',
    name: 'Azi',
    category: 'Pet kosztüm',
    rarity: 'common',
    sources: [],
    image: '/images/pets/azi.png',
    wikiUrl: 'https://wiki.venor2.hu/items/53006',
  },
  {
    id: 'leonidasz',
    name: 'Leonidász',
    category: 'Pet kosztüm',
    rarity: 'common',
    sources: [],
    image: '/images/pets/leonidasz.png',
    wikiUrl: 'https://wiki.venor2.hu/items/53010',
  },
  {
    id: 'porky',
    name: 'Porky',
    category: 'Pet kosztüm',
    rarity: 'common',
    sources: [],
    image: '/images/pets/porky.png',
    wikiUrl: 'https://wiki.venor2.hu/items/53012',
  },
  {
    id: 'pufok-minihoher',
    name: 'Pufók Minihóhér',
    category: 'Pet kosztüm',
    rarity: 'common',
    sources: [],
    image: '/images/pets/pufok-minihoher.png',
    wikiUrl: 'https://wiki.venor2.hu/items/53014',
  },
  {
    id: 'arany-minihoher',
    name: 'Arany Minihóhér',
    category: 'Pet kosztüm',
    rarity: 'common',
    sources: [],
    image: '/images/pets/arany-minihoher.png',
    wikiUrl: 'https://wiki.venor2.hu/items/53015',
  },
  {
    id: 'ho-leonidasz',
    name: 'Hó-Leonidász',
    category: 'Pet kosztüm',
    rarity: 'common',
    sources: [],
    image: '/images/pets/ho-leonidasz.png',
    wikiUrl: 'https://wiki.venor2.hu/items/53018',
  },
  {
    id: 'szoszi',
    name: 'Szöszi',
    category: 'Pet kosztüm',
    rarity: 'common',
    sources: [],
    image: '/images/pets/szoszi.png',
    wikiUrl: 'https://wiki.venor2.hu/items/53232',
  },
  {
    id: 'holdlampas-kek',
    name: 'Holdlámpás (Kék)',
    category: 'Pet kosztüm',
    rarity: 'common',
    sources: [],
    image: '/images/pets/holdlampas-kek.png',
    wikiUrl: 'https://wiki.venor2.hu/items/53240',
  },
  {
    id: 'holdlampas-narancs',
    name: 'Holdlámpás (Narancs)',
    category: 'Pet kosztüm',
    rarity: 'common',
    sources: [],
    image: '/images/pets/holdlampas-narancs.png',
    wikiUrl: 'https://wiki.venor2.hu/items/53241',
  },
  {
    id: 'gobby',
    name: 'Gobby',
    category: 'Pet kosztüm',
    rarity: 'common',
    sources: [],
    image: '/images/pets/gobby.png',
    wikiUrl: 'https://wiki.venor2.hu/items/53248',
  },
  {
    id: 'peneszlovag',
    name: 'Penészlovag',
    category: 'Pet kosztüm',
    rarity: 'common',
    sources: [],
    image: '/images/pets/peneszlovag.png',
    wikiUrl: 'https://wiki.venor2.hu/items/53250',
  },
  {
    id: 'vulkira-a-tuzmacska',
    name: 'Vulkira a tűzmacska',
    category: 'Pet kosztüm',
    rarity: 'common',
    sources: [],
    image: '/images/pets/vulkira-a-tuzmacska.png',
    wikiUrl: 'https://wiki.venor2.hu/items/53282',
  },
  {
    id: 'voros',
    name: 'Vörös',
    category: 'Pet kosztüm',
    rarity: 'common',
    sources: [],
    image: '/images/pets/voros.png',
    wikiUrl: 'https://wiki.venor2.hu/items/53288',
  },
  {
    id: 'turazo',
    name: 'Túrázó',
    category: 'Pet kosztüm',
    rarity: 'common',
    sources: [],
    image: '/images/pets/turazo.png',
    wikiUrl: 'https://wiki.venor2.hu/items/210001',
  },
  {
    id: 'venori',
    name: 'Venori',
    category: 'Pet kosztüm',
    rarity: 'common',
    sources: [],
    image: '/images/pets/venori.png',
    wikiUrl: 'https://wiki.venor2.hu/items/210002',
  },
  {
    id: 'gombi',
    name: 'Gömbi',
    category: 'Pet kosztüm',
    rarity: 'common',
    sources: [],
    image: '/images/pets/gombi.png',
    wikiUrl: 'https://wiki.venor2.hu/items/210005',
  },
  {
    id: 'dumbyno',
    name: 'Dumbyno',
    category: 'Pet kosztüm',
    rarity: 'common',
    sources: [],
    image: '/images/pets/dumbyno.png',
    wikiUrl: 'https://wiki.venor2.hu/items/210018',
  },
  {
    id: 'mumbyno',
    name: 'Mumbyno',
    category: 'Pet kosztüm',
    rarity: 'common',
    sources: [],
    image: '/images/pets/mumbyno.png',
    wikiUrl: 'https://wiki.venor2.hu/items/210019',
  },
  {
    id: 'don-rofington',
    name: 'Don Röfington',
    category: 'Pet kosztüm',
    rarity: 'common',
    sources: [],
    image: '/images/pets/don-rofington.png',
    wikiUrl: 'https://wiki.venor2.hu/items/210023',
  },
  {
    id: 'blaze',
    name: 'Blaze',
    category: 'Pet kosztüm',
    rarity: 'common',
    sources: [],
    image: '/images/pets/blaze.png',
    wikiUrl: 'https://wiki.venor2.hu/items/210058',
  },
  {
    id: 'zafira',
    name: 'Zafira',
    category: 'Pet kosztüm',
    rarity: 'common',
    sources: [],
    image: '/images/pets/zafira.png',
    wikiUrl: 'https://wiki.venor2.hu/items/210059',
  },
  {
    id: 'luka',
    name: 'Luka',
    category: 'Pet kosztüm',
    rarity: 'common',
    sources: [],
    image: '/images/pets/luka.png',
    wikiUrl: 'https://wiki.venor2.hu/items/210070',
  },
  {
    id: 'cotton-papagaja',
    name: 'Cotton Papagája',
    category: 'Pet kosztüm',
    rarity: 'common',
    sources: [],
    image: '/images/pets/cotton-papagaja.png',
    wikiUrl: 'https://wiki.venor2.hu/items/210078',
  },
  {
    id: 'okidoki',
    name: 'OkiDoki',
    category: 'Pet kosztüm',
    rarity: 'common',
    sources: [],
    image: '/images/pets/okidoki.png',
    wikiUrl: 'https://wiki.venor2.hu/items/210082',
  },
  {
    id: 'grim',
    name: 'Grim',
    category: 'Pet kosztüm',
    rarity: 'common',
    sources: [],
    image: '/images/pets/grim.png',
    wikiUrl: 'https://wiki.venor2.hu/items/210083',
  },
  {
    id: 'slim',
    name: 'Slim',
    category: 'Pet kosztüm',
    rarity: 'common',
    sources: [],
    image: '/images/pets/slim.png',
    wikiUrl: 'https://wiki.venor2.hu/items/210084',
  },
  {
    id: 'bambusz',
    name: 'Bambusz',
    category: 'Pet kosztüm',
    rarity: 'common',
    sources: [],
    image: '/images/pets/bambusz.png',
    wikiUrl: 'https://wiki.venor2.hu/items/210085',
  },
  {
    id: 'venorax',
    name: 'Venorax',
    category: 'Pet kosztüm',
    rarity: 'common',
    sources: [],
    image: '/images/pets/venorax.png',
    wikiUrl: 'https://wiki.venor2.hu/items/210087',
  },
  {
    id: 'pihe',
    name: 'Pihe',
    category: 'Pet kosztüm',
    rarity: 'common',
    sources: [],
    image: '/images/pets/pihe.png',
    wikiUrl: 'https://wiki.venor2.hu/items/210088',
  },
  {
    id: 'pyroth',
    name: 'Pyroth',
    category: 'Pet kosztüm',
    rarity: 'common',
    sources: [],
    image: '/images/pets/pyroth.png',
    wikiUrl: 'https://wiki.venor2.hu/items/210089',
  },
  {
    id: 'fagyos-lehelet',
    name: 'Fagyos lehelet',
    category: 'Pet kosztüm',
    rarity: 'common',
    sources: [],
    image: '/images/pets/fagyos-lehelet.png',
    wikiUrl: 'https://wiki.venor2.hu/items/210090',
  },
  {
    id: 'aprodka',
    name: 'Apródka',
    category: 'Pet kosztüm',
    rarity: 'common',
    sources: [],
    image: '/images/pets/aprodka.png',
    wikiUrl: 'https://wiki.venor2.hu/items/210106',
  },
  {
    id: 'spidogi',
    name: 'Spidogi',
    category: 'Pet kosztüm',
    rarity: 'common',
    sources: [],
    image: '/images/pets/spidogi.png',
    wikiUrl: 'https://wiki.venor2.hu/items/210112',
  },
  {
    id: 'mezi',
    name: 'Mézi',
    category: 'Pet kosztüm',
    rarity: 'common',
    sources: [],
    image: '/images/pets/mezi.png',
    wikiUrl: 'https://wiki.venor2.hu/items/210116',
  },
  {
    id: '107-es-ceh-topije',
    name: '107-es céh Töpije',
    category: 'Pet kosztüm',
    rarity: 'common',
    sources: [],
    image: '/images/pets/107-es-ceh-topije.png',
    wikiUrl: 'https://wiki.venor2.hu/items/210121',
  },
  {
    id: 'vigyor-kandur',
    name: 'Vigyor Kandúr',
    category: 'Pet kosztüm',
    rarity: 'common',
    sources: [],
    image: '/images/pets/vigyor-kandur.png',
    wikiUrl: 'https://wiki.venor2.hu/items/210132',
  },
  {
    id: 'groot',
    name: 'Groot',
    category: 'Pet kosztüm',
    rarity: 'common',
    sources: [],
    image: '/images/pets/groot.png',
    wikiUrl: 'https://wiki.venor2.hu/items/210139',
  },
  {
    id: 'leafy',
    name: 'Leafy',
    category: 'Pet kosztüm',
    rarity: 'common',
    sources: [],
    image: '/images/pets/leafy.png',
    wikiUrl: 'https://wiki.venor2.hu/items/210141',
  },
  {
    id: 'szipi',
    name: 'Szipi',
    category: 'Pet kosztüm',
    rarity: 'common',
    sources: [],
    image: '/images/pets/szipi.png',
    wikiUrl: 'https://wiki.venor2.hu/items/210142',
  },
  {
    id: 'mambo',
    name: 'Mambo',
    category: 'Pet kosztüm',
    rarity: 'common',
    sources: [],
    image: '/images/pets/mambo.png',
    wikiUrl: 'https://wiki.venor2.hu/items/210143',
  },
  {
    id: 'taktik',
    name: 'TakTik',
    category: 'Pet kosztüm',
    rarity: 'common',
    sources: [],
    image: '/images/pets/taktik.png',
    wikiUrl: 'https://wiki.venor2.hu/items/210146',
  },
  {
    id: 'szelloke',
    name: 'Szellőke',
    category: 'Pet kosztüm',
    rarity: 'common',
    sources: [],
    image: '/images/pets/szelloke.png',
    wikiUrl: 'https://wiki.venor2.hu/items/210147',
  },
  {
    id: 'diana',
    name: 'Diana',
    category: 'Pet kosztüm',
    rarity: 'common',
    sources: [],
    image: '/images/pets/diana.png',
    wikiUrl: 'https://wiki.venor2.hu/items/210148',
  },
  {
    id: 'kek-lang',
    name: 'Kék Láng',
    category: 'Pet kosztüm',
    rarity: 'common',
    sources: [],
    image: '/images/pets/kek-lang.png',
    wikiUrl: 'https://wiki.venor2.hu/items/210164',
  },
  {
    id: 'skelejerry',
    name: 'SkeleJerry',
    category: 'Pet kosztüm',
    rarity: 'common',
    sources: [],
    image: '/images/pets/skelejerry.png',
    wikiUrl: 'https://wiki.venor2.hu/items/210175',
  },
  {
    id: 'skeletom',
    name: 'SkeleTom',
    category: 'Pet kosztüm',
    rarity: 'common',
    sources: [],
    image: '/images/pets/skeletom.png',
    wikiUrl: 'https://wiki.venor2.hu/items/210176',
  },
  {
    id: 'fenyek-orzoje',
    name: 'Fények Örzője',
    category: 'Pet kosztüm',
    rarity: 'common',
    sources: [],
    image: '/images/pets/fenyek-orzoje.png',
    wikiUrl: 'https://wiki.venor2.hu/items/210178',
  },
  {
    id: 'cerberus',
    name: 'Cerberus',
    category: 'Pet kosztüm',
    rarity: 'common',
    sources: [],
    image: '/images/pets/cerberus.png',
    wikiUrl: 'https://wiki.venor2.hu/items/210180',
  },
  {
    id: 'bagi',
    name: 'Bagi',
    category: 'Pet kosztüm',
    rarity: 'common',
    sources: [],
    image: '/images/pets/bagi.png',
    wikiUrl: 'https://wiki.venor2.hu/items/210186',
  },
  {
    id: 'cerka',
    name: 'Cerka',
    category: 'Pet kosztüm',
    rarity: 'common',
    sources: [],
    image: '/images/pets/cerka.png',
    wikiUrl: 'https://wiki.venor2.hu/items/210187',
  },
  {
    id: 'kekike',
    name: 'Kékike',
    category: 'Pet kosztüm',
    rarity: 'common',
    sources: [],
    image: '/images/pets/kekike.png',
    wikiUrl: 'https://wiki.venor2.hu/items/210193',
  },
  {
    id: 'uszogumi',
    name: 'Úszógumi',
    category: 'Pet kosztüm',
    rarity: 'common',
    sources: [],
    image: '/images/pets/uszogumi.png',
    wikiUrl: 'https://wiki.venor2.hu/items/210194',
  },
  {
    id: 'zsugabuga',
    name: 'Zsugabuga',
    category: 'Pet kosztüm',
    rarity: 'common',
    sources: [],
    image: '/images/pets/zsugabuga.png',
    wikiUrl: 'https://wiki.venor2.hu/items/210199',
  },
  {
    id: 'a-fekete-gyongy',
    name: 'A fekete gyöngy',
    category: 'Pet kosztüm',
    rarity: 'common',
    sources: [],
    image: '/images/pets/a-fekete-gyongy.png',
    wikiUrl: 'https://wiki.venor2.hu/items/210207',
  },
  {
    id: 'kiraly-pingvin',
    name: 'Király pingvin',
    category: 'Pet kosztüm',
    rarity: 'common',
    sources: [],
    image: '/images/pets/kiraly-pingvin.png',
    wikiUrl: 'https://wiki.venor2.hu/items/210226',
  },
  {
    id: 'luna',
    name: 'Luna',
    category: 'Pet kosztüm',
    rarity: 'common',
    sources: [],
    image: '/images/pets/luna.png',
    wikiUrl: 'https://wiki.venor2.hu/items/210236',
  },
  {
    id: 'moki',
    name: 'Moki',
    category: 'Pet kosztüm',
    rarity: 'common',
    sources: [],
    image: '/images/pets/moki.png',
    wikiUrl: 'https://wiki.venor2.hu/items/210238',
  },
  {
    id: 'moka',
    name: 'Moka',
    category: 'Pet kosztüm',
    rarity: 'common',
    sources: [],
    image: '/images/pets/moka.png',
    wikiUrl: 'https://wiki.venor2.hu/items/210239',
  },
  {
    id: 'villam',
    name: 'Villám',
    category: 'Pet kosztüm',
    rarity: 'common',
    sources: [],
    image: '/images/pets/villam.png',
    wikiUrl: 'https://wiki.venor2.hu/items/210240',
  },
  {
    id: 'idorion',
    name: 'Idorion',
    category: 'Pet kosztüm',
    rarity: 'common',
    sources: [],
    image: '/images/pets/idorion.png',
    wikiUrl: 'https://wiki.venor2.hu/items/210241',
  },
  {
    id: 'chiyan',
    name: 'Chiyan',
    category: 'Pet kosztüm',
    rarity: 'common',
    sources: [],
    image: '/images/pets/chiyan.png',
    wikiUrl: 'https://wiki.venor2.hu/items/210242',
  },
  {
    id: 'lombo',
    name: 'Lombo',
    category: 'Pet kosztüm',
    rarity: 'common',
    sources: [],
    image: '/images/pets/lombo.png',
    wikiUrl: 'https://wiki.venor2.hu/items/210243',
  },
  {
    id: 'rak-ur',
    name: 'Rák Úr',
    category: 'Pet kosztüm',
    rarity: 'common',
    sources: [],
    image: '/images/pets/rak-ur.png',
    wikiUrl: 'https://wiki.venor2.hu/items/210383',
  },
  {
    id: 'asmodeus-fonixe',
    name: 'Asmodeus főnixe',
    category: 'Pet kosztüm',
    rarity: 'common',
    sources: [],
    image: '/images/pets/asmodeus-fonixe.png',
    wikiUrl: 'https://wiki.venor2.hu/items/211101',
  },
  {
    id: 'megvaltas-fonixe',
    name: 'Megváltás főnixe',
    category: 'Pet kosztüm',
    rarity: 'common',
    sources: [],
    image: '/images/pets/megvaltas-fonixe.png',
    wikiUrl: 'https://wiki.venor2.hu/items/211102',
  },
  {
    id: 'tiktak',
    name: 'TikTak',
    category: 'Pet kosztüm',
    rarity: 'common',
    sources: [],
    image: '/images/pets/tiktak.png',
    wikiUrl: 'https://wiki.venor2.hu/items/211152',
  },
  {
    id: 'igli',
    name: 'Igli',
    category: 'Pet kosztüm',
    rarity: 'common',
    sources: [],
    image: '/images/pets/igli.png',
    wikiUrl: 'https://wiki.venor2.hu/items/211168',
  },
  {
    id: 'kis-rak',
    name: 'Kis rák',
    category: 'Pet kosztüm',
    rarity: 'common',
    sources: [],
    image: '/images/pets/kis-rak.png',
    wikiUrl: 'https://wiki.venor2.hu/items/211169',
  },
  {
    id: 'voraki',
    name: 'Voraki',
    category: 'Pet kosztüm',
    rarity: 'common',
    sources: [],
    image: '/images/pets/voraki.png',
    wikiUrl: 'https://wiki.venor2.hu/items/211170',
  },
];
