import type { Pet } from './types';

/**
 * ============================================================
 *  PET-LISTA
 * ============================================================
 *
 * Ezt a fájlt a scripts/import-pets.mjs generálta a szerver wikijéről:
 * ./wiki-pets.json
 *
 * Kézzel is nyugodtan szerkeszthető, de egy újabb import felülírja – tartós
 * változtatáshoz inkább a wikit vagy a szkriptet igazítsd.
 *
 * A `bonuses` a játék nyers apply-mezőiből jön, a wiki magyar feliratával
 * (pl. "Szörnyek elleni erő +3%"). A `rarity` a wikiben nincs benne, ezért
 * minden petnél az importálás alapértéke áll – ha akarod, kézzel állítsd:
 *
 *   rarity = 'common' | 'rare' | 'epic' | 'legendary'
 *
 * FONTOS: az `id` mezőt utólag NE írd át! A látogatók pipái ez alapján
 * vannak elmentve, egy átnevezett id-nél elveszik a jelölés. Az importáló
 * szkript ezért a meglévő id-ket név alapján megtartja.
 */

/** Amíg true, az oldal tetején figyelmeztet, hogy ezek példaadatok. */
export const IS_SAMPLE_DATA = false;

export const PETS: Pet[] = [
  {
    id: 'azika',
    name: 'Azika',
    category: 'Pet kosztüm',
    rarity: 'common',
    sources: ['boss', 'dungeon'],
    acquisition: [
      { kind: 'boss', text: 'Esik a(z) Azrael nevű bossból' },
      { kind: 'dungeon', text: 'Megszerezhető innen: Azrael katakombája' },
    ],
    location: 'Azrael',
    bonuses: ['Szörnyek elleni erő +1%', 'Sötétség ereje +3%'],
    image: '/images/pets/azika.png',
    wikiUrl: 'https://wiki.venor2.hu/items/53005',
  },
  {
    id: 'azi',
    name: 'Azi',
    category: 'Pet kosztüm',
    rarity: 'common',
    sources: ['shop'],
    acquisition: [
      { kind: 'shop', text: 'Megvásárolható Theowahdan NPC-nél', costs: ['100 db Azrael ládája', '5000 db Finom kelme', '5 db Azika'] },
    ],
    location: 'Theowahdan',
    npcs: ['Theowahdan'],
    bonuses: ['Szörnyek elleni erő +2%', 'Sötétség ereje +5%'],
    image: '/images/pets/azi.png',
    wikiUrl: 'https://wiki.venor2.hu/items/53006',
  },
  {
    id: 'leonidasz',
    name: 'Leonidász',
    category: 'Pet kosztüm',
    rarity: 'common',
    sources: ['shop'],
    acquisition: [
      { kind: 'shop', text: 'Megvásárolható Vegyeskereskedő Eladónő NPC-nél', costs: ['3000 db Kő-töredék'] },
    ],
    location: 'Vegyeskereskedő Eladónő',
    npcs: ['Vegyeskereskedő Eladónő'],
    bonuses: ['Kövek elleni erő +3%'],
    image: '/images/pets/leonidasz.png',
    wikiUrl: 'https://wiki.venor2.hu/items/53010',
  },
  {
    id: 'porky',
    name: 'Porky',
    category: 'Pet kosztüm',
    rarity: 'common',
    sources: ['boss', 'dungeon'],
    acquisition: [
      { kind: 'boss', text: 'Esik a(z) Razador nevű bossból' },
      { kind: 'dungeon', text: 'Megszerezhető innen: Razador erődje' },
    ],
    location: 'Razador',
    bonuses: ['Főszörnyek elleni erő +2%', 'Tűz ereje +3%'],
    image: '/images/pets/porky.png',
    wikiUrl: 'https://wiki.venor2.hu/items/53012',
  },
  {
    id: 'pufok-minihoher',
    name: 'Pufók Minihóhér',
    category: 'Pet kosztüm',
    rarity: 'common',
    sources: ['boss', 'dungeon'],
    acquisition: [
      { kind: 'boss', text: 'Esik a(z) Jotun Thrym nevű bossból' },
      { kind: 'dungeon', text: 'Megszerezhető innen: Jotun erdeje' },
    ],
    location: 'Jotun Thrym',
    bonuses: ['Kövek elleni erő +1%', 'Föld ereje +3%'],
    image: '/images/pets/pufok-minihoher.png',
    wikiUrl: 'https://wiki.venor2.hu/items/53014',
  },
  {
    id: 'arany-minihoher',
    name: 'Arany Minihóhér',
    category: 'Pet kosztüm',
    rarity: 'common',
    sources: ['shop'],
    acquisition: [
      { kind: 'shop', text: 'Megvásárolható Theowahdan NPC-nél', costs: ['200 db Földkő', '2500 db Lélekkő', '2500 db Nemes fa', '3 db Pufók Minihóhér'] },
    ],
    location: 'Theowahdan',
    npcs: ['Theowahdan'],
    bonuses: ['Kövek elleni erő +2%', 'Föld ereje +5%'],
    image: '/images/pets/arany-minihoher.png',
    wikiUrl: 'https://wiki.venor2.hu/items/53015',
  },
  {
    id: 'ho-leonidasz',
    name: 'Hó-Leonidász',
    category: 'Pet kosztüm',
    rarity: 'common',
    sources: ['shop'],
    acquisition: [
      { kind: 'shop', text: 'Megvásárolható Vegyeskereskedő Eladónő NPC-nél', costs: ['25 000 db Kő-töredék', '1500 db Legendás kő-töredék'] },
    ],
    location: 'Vegyeskereskedő Eladónő',
    npcs: ['Vegyeskereskedő Eladónő'],
    bonuses: ['Kövek elleni erő +5%'],
    image: '/images/pets/ho-leonidasz.png',
    wikiUrl: 'https://wiki.venor2.hu/items/53018',
  },
  {
    id: 'szoszi',
    name: 'Szöszi',
    category: 'Pet kosztüm',
    rarity: 'common',
    sources: ['dungeon', 'shop'],
    acquisition: [
      { kind: 'dungeon', text: 'Megszerezhető innen: Zodiákus templom' },
      { kind: 'shop', text: 'Megvásárolható Zodiákus kereskedő NPC-nél', costs: ['10 db Zodiákus pont', '50 db Vörös zodiákus szelence', '50 db Kék zodiákus szelence'] },
    ],
    location: 'Zodiákus templom',
    npcs: ['Zodiákus kereskedő'],
    bonuses: ['Zodiákus szörnyek elleni erő +10%'],
    image: '/images/pets/szoszi.png',
    wikiUrl: 'https://wiki.venor2.hu/items/53232',
  },
  {
    id: 'holdlampas-kek',
    name: 'Holdlámpás (Kék)',
    category: 'Pet kosztüm',
    rarity: 'common',
    sources: ['drop', 'event'],
    acquisition: [
      { kind: 'drop', text: 'Kinyerhető ebből a ládából: HF láda' },
      { kind: 'event', text: 'Elérhető ez alatt: Holdfény kincsesláda Event' },
    ],
    bonuses: ['Szörnyek elleni erő +3%', 'Max. TP +1500'],
    image: '/images/pets/holdlampas-kek.png',
    wikiUrl: 'https://wiki.venor2.hu/items/53240',
  },
  {
    id: 'holdlampas-narancs',
    name: 'Holdlámpás (Narancs)',
    category: 'Pet kosztüm',
    rarity: 'common',
    sources: ['drop', 'event'],
    acquisition: [
      { kind: 'drop', text: 'Kinyerhető ebből a ládából: Nagy HF láda' },
      { kind: 'event', text: 'Elérhető ez alatt: Holdfény kincsesláda Event' },
    ],
    bonuses: ['Szörnyek elleni erő +5%', 'Max. TP +2000'],
    image: '/images/pets/holdlampas-narancs.png',
    wikiUrl: 'https://wiki.venor2.hu/items/53241',
  },
  {
    id: 'gobby',
    name: 'Gobby',
    category: 'Pet kosztüm',
    rarity: 'common',
    sources: ['drop', 'shop'],
    acquisition: [
      { kind: 'drop', text: 'Kinyerhető ebből a ládából: Premium Goblin láda' },
      { kind: 'shop', text: 'Megvásárolható Fő Goblin NPC-nél', costs: ['250 db Prémium goblin láda'] },
    ],
    location: 'Fő Goblin',
    npcs: ['Fő Goblin'],
    bonuses: ['Átlagos károk 2%', 'Mágikus/közelharci támadás +1%'],
    image: '/images/pets/gobby.png',
    wikiUrl: 'https://wiki.venor2.hu/items/53248',
  },
  {
    id: 'peneszlovag',
    name: 'Penészlovag',
    category: 'Pet kosztüm',
    rarity: 'common',
    sources: ['event', 'shop'],
    acquisition: [
      { kind: 'event', text: 'Elérhető ez alatt: Napi Töredék Event' },
      { kind: 'shop', text: 'Megvásárolható Vegyeskereskedő Eladónő NPC-nél', costs: ['10 000 db Gombaspórák'] },
    ],
    location: 'Vegyeskereskedő Eladónő',
    npcs: ['Vegyeskereskedő Eladónő'],
    bonuses: ['Szörnyek elleni erő +3%', 'Dupla tárgy dobás esélye +1%'],
    image: '/images/pets/peneszlovag.png',
    wikiUrl: 'https://wiki.venor2.hu/items/53250',
  },
  {
    id: 'vulkira-a-tuzmacska',
    name: 'Vulkira a tűzmacska',
    category: 'Pet kosztüm',
    rarity: 'common',
    sources: ['drop', 'event'],
    acquisition: [
      { kind: 'drop', text: 'Kinyerhető ebből a ládából: Tarot Arany láda' },
      { kind: 'event', text: 'Elérhető ez alatt: Tarot Event' },
    ],
    bonuses: ['Átlagos károk 1%', 'Max. TP +1000', 'Sungma Erő +1'],
    image: '/images/pets/vulkira-a-tuzmacska.png',
    wikiUrl: 'https://wiki.venor2.hu/items/53282',
  },
  {
    id: 'voros',
    name: 'Vörös',
    category: 'Pet kosztüm',
    rarity: 'common',
    sources: ['dungeon', 'shop'],
    acquisition: [
      { kind: 'dungeon', text: 'Megszerezhető innen: Zodiákus templom' },
      { kind: 'shop', text: 'Megvásárolható Zodiákus kereskedő NPC-nél', costs: ['100 db Zodiákus pont', '500 db Vörös zodiákus szelence', '500 db Kék zodiákus szelence'] },
    ],
    location: 'Zodiákus templom',
    npcs: ['Zodiákus kereskedő'],
    bonuses: ['Zodiákus szörnyek elleni erő +5%', 'Átlagos károk 2%'],
    image: '/images/pets/voros.png',
    wikiUrl: 'https://wiki.venor2.hu/items/53288',
  },
  {
    id: 'turazo',
    name: 'Túrázó',
    category: 'Pet kosztüm',
    rarity: 'common',
    sources: ['shop'],
    acquisition: [
      { kind: 'shop', text: 'Megvásárolható Kalandorok nagyapja NPC-nél', costs: ['10 db Kalandorok lelke'] },
    ],
    location: 'Kalandorok nagyapja',
    npcs: ['Kalandorok nagyapja'],
    bonuses: ['Szörnyek elleni erő +3%', 'Varázssebesség +5%'],
    image: '/images/pets/turazo.png',
    wikiUrl: 'https://wiki.venor2.hu/items/210001',
  },
  {
    id: 'venori',
    name: 'Venori',
    category: 'Pet kosztüm',
    rarity: 'common',
    sources: ['drop', 'event'],
    acquisition: [
      { kind: 'drop', text: 'Kinyerhető ebből a ládából: Nagy Venor láda' },
      { kind: 'event', text: 'Elérhető ez alatt: Venor Event' },
    ],
    bonuses: ['Szörnyek elleni erő +5%', 'Átlagos károk 3%'],
    image: '/images/pets/venori.png',
    wikiUrl: 'https://wiki.venor2.hu/items/210002',
  },
  {
    id: 'gombi',
    name: 'Gömbi',
    category: 'Pet kosztüm',
    rarity: 'common',
    sources: ['drop', 'event'],
    acquisition: [
      { kind: 'drop', text: 'Kinyerhető ebből a ládából: Gyemant Hal láda' },
      { kind: 'event', text: 'Elérhető ez alatt: Halláda Event' },
    ],
    bonuses: ['Erő +3', 'Ügyesség +3', 'Intelligencia +3', 'Életerő +3'],
    image: '/images/pets/gombi.png',
    wikiUrl: 'https://wiki.venor2.hu/items/210005',
  },
  {
    id: 'dumbyno',
    name: 'Dumbyno',
    category: 'Pet kosztüm',
    rarity: 'common',
    sources: ['shop'],
    acquisition: [
      { kind: 'shop', text: 'Megvásárolható Theowahdan NPC-nél', costs: ['100 db Elefánt lélek', '5000 db Harmat láda'] },
    ],
    location: 'Theowahdan',
    npcs: ['Theowahdan'],
    bonuses: ['Szörnyek elleni erő +4%', 'Dupla tárgy dobás esélye +1%'],
    image: '/images/pets/dumbyno.png',
    wikiUrl: 'https://wiki.venor2.hu/items/210018',
  },
  {
    id: 'mumbyno',
    name: 'Mumbyno',
    category: 'Pet kosztüm',
    rarity: 'common',
    sources: ['shop'],
    acquisition: [
      { kind: 'shop', text: 'Megvásárolható Theowahdan NPC-nél', costs: ['1000 db Elefánt lélek', '50 000 db Kő-töredék'] },
    ],
    location: 'Theowahdan',
    npcs: ['Theowahdan'],
    bonuses: ['Szörnyek elleni erő +5%', 'Dupla tárgy dobás esélye +1%'],
    image: '/images/pets/mumbyno.png',
    wikiUrl: 'https://wiki.venor2.hu/items/210019',
  },
  {
    id: 'don-rofington',
    name: 'Don Röfington',
    category: 'Pet kosztüm',
    rarity: 'common',
    sources: ['shop'],
    acquisition: [
      { kind: 'shop', text: 'Megvásárolható Kövek árusa NPC-nél', costs: ['200 db Gyémánt kőszilánk'] },
    ],
    location: 'Kövek árusa',
    npcs: ['Kövek árusa'],
    bonuses: ['Kövek elleni erő +5%', 'Szörnyek elleni erő +3%'],
    image: '/images/pets/don-rofington.png',
    wikiUrl: 'https://wiki.venor2.hu/items/210023',
  },
  {
    id: 'blaze',
    name: 'Blaze',
    category: 'Pet kosztüm',
    rarity: 'common',
    sources: ['shop'],
    acquisition: [
      { kind: 'shop', text: 'Megvásárolható Theowahdan NPC-nél', costs: ['200 db Tűzkő', '5 db Razador szarva', '3 db Porky'] },
    ],
    location: 'Theowahdan',
    npcs: ['Theowahdan'],
    bonuses: ['Főszörnyek elleni erő +2%', 'Tűz ereje +5%'],
    image: '/images/pets/blaze.png',
    wikiUrl: 'https://wiki.venor2.hu/items/210058',
  },
  {
    id: 'zafira',
    name: 'Zafira',
    category: 'Pet kosztüm',
    rarity: 'common',
    sources: [],
    bonuses: ['Kövek elleni erő +5%'],
    image: '/images/pets/zafira.png',
    wikiUrl: 'https://wiki.venor2.hu/items/210059',
  },
  {
    id: 'luka',
    name: 'Luka',
    category: 'Pet kosztüm',
    rarity: 'common',
    sources: [],
    bonuses: ['Szörnyek elleni erő +5%'],
    image: '/images/pets/luka.png',
    wikiUrl: 'https://wiki.venor2.hu/items/210070',
  },
  {
    id: 'cotton-papagaja',
    name: 'Cotton Papagája',
    category: 'Pet kosztüm',
    rarity: 'common',
    sources: ['drop', 'shop'],
    acquisition: [
      { kind: 'drop', text: 'Kinyerhető ebből a ládából: Rothadt fadoboz' },
      { kind: 'shop', text: 'Megvásárolható Kalóz Kapitány NPC-nél', costs: ['600 db Farönk'] },
    ],
    location: 'Kalóz Kapitány',
    npcs: ['Kalóz Kapitány'],
    bonuses: ['Szörnyek elleni erő +2%', 'Kövek elleni erő +3%'],
    image: '/images/pets/cotton-papagaja.png',
    wikiUrl: 'https://wiki.venor2.hu/items/210078',
  },
  {
    id: 'okidoki',
    name: 'OkiDoki',
    category: 'Pet kosztüm',
    rarity: 'common',
    sources: ['drop', 'event'],
    acquisition: [
      { kind: 'drop', text: 'Kinyerhető ebből a ládából: Arany Okey láda' },
      { kind: 'event', text: 'Elérhető ez alatt: Okey Láda Event' },
    ],
    bonuses: ['Főszörnyek elleni erő +3%'],
    image: '/images/pets/okidoki.png',
    wikiUrl: 'https://wiki.venor2.hu/items/210082',
  },
  {
    id: 'grim',
    name: 'Grim',
    category: 'Pet kosztüm',
    rarity: 'common',
    sources: ['boss', 'dungeon'],
    acquisition: [
      { kind: 'boss', text: 'Esik a(z) Kaszás nevű bossból' },
      { kind: 'dungeon', text: 'Megszerezhető innen: Démon torony' },
    ],
    location: 'Kaszás',
    bonuses: ['Szörnyek elleni erő +1%', 'Sötétség ereje +3%'],
    image: '/images/pets/grim.png',
    wikiUrl: 'https://wiki.venor2.hu/items/210083',
  },
  {
    id: 'slim',
    name: 'Slim',
    category: 'Pet kosztüm',
    rarity: 'common',
    sources: ['boss', 'dungeon', 'shop'],
    acquisition: [
      { kind: 'boss', text: 'Esik a(z) Kék halál nevű bossból' },
      { kind: 'dungeon', text: 'Megszerezhető innen: Démon torony' },
      { kind: 'shop', text: 'Megvásárolható Theowahdan NPC-nél', costs: ['10 db Grim', '2000 db Kő-töredék'] },
    ],
    location: 'Kék halál',
    npcs: ['Theowahdan'],
    bonuses: ['Szörnyek elleni erő +2%', 'Sötétség ereje +5%'],
    image: '/images/pets/slim.png',
    wikiUrl: 'https://wiki.venor2.hu/items/210084',
  },
  {
    id: 'bambusz',
    name: 'Bambusz',
    category: 'Pet kosztüm',
    rarity: 'common',
    sources: ['drop', 'event', 'shop'],
    acquisition: [
      { kind: 'drop', text: 'Kinyerhető ebből a ládából: Villam láda' },
      { kind: 'event', text: 'Elérhető ez alatt: Villám Element Event' },
      { kind: 'shop', text: 'Megvásárolható Elementális kereskedő (Villám) NPC-nél', costs: ['100 db Villám láda'] },
    ],
    location: 'Elementális kereskedő (Villám)',
    npcs: ['Elementális kereskedő (Villám)'],
    bonuses: ['Átlagos károk 2%', 'Szörnyek elleni erő +2%'],
    image: '/images/pets/bambusz.png',
    wikiUrl: 'https://wiki.venor2.hu/items/210085',
  },
  {
    id: 'venorax',
    name: 'Venorax',
    category: 'Pet kosztüm',
    rarity: 'common',
    sources: ['drop', 'dungeon'],
    acquisition: [
      { kind: 'drop', text: 'Kinyerhető ebből a ládából: Meley láda' },
      { kind: 'dungeon', text: 'Megszerezhető innen: Meley barlangja' },
    ],
    location: 'Meley barlangja',
    bonuses: ['Átlagos károk 2%', 'Tűz ereje +5%'],
    image: '/images/pets/venorax.png',
    wikiUrl: 'https://wiki.venor2.hu/items/210087',
  },
  {
    id: 'pihe',
    name: 'Pihe',
    category: 'Pet kosztüm',
    rarity: 'common',
    sources: ['boss', 'dungeon'],
    acquisition: [
      { kind: 'boss', text: 'Esik a(z) Nemere nevű bossból' },
      { kind: 'dungeon', text: 'Megszerezhető innen: Nemere őrtornya' },
    ],
    location: 'Nemere',
    bonuses: ['Főszörnyek elleni erő +2%', 'Jég ereje +3%'],
    image: '/images/pets/pihe.png',
    wikiUrl: 'https://wiki.venor2.hu/items/210088',
  },
  {
    id: 'pyroth',
    name: 'Pyroth',
    category: 'Pet kosztüm',
    rarity: 'common',
    sources: ['boss', 'dungeon'],
    acquisition: [
      { kind: 'boss', text: 'Esik a(z) Sárkánykirály Akzadur nevű bossból' },
      { kind: 'dungeon', text: 'Megszerezhető innen: Sárkánykirály palotája' },
    ],
    location: 'Sárkánykirály Akzadur',
    bonuses: ['Mágikus/közelharci támadás +2%', 'Max. TP +1500'],
    image: '/images/pets/pyroth.png',
    wikiUrl: 'https://wiki.venor2.hu/items/210089',
  },
  {
    id: 'fagyos-lehelet',
    name: 'Fagyos lehelet',
    category: 'Pet kosztüm',
    rarity: 'common',
    sources: ['shop'],
    acquisition: [
      { kind: 'shop', text: 'Megvásárolható Theowahdan NPC-nél', costs: ['200 db Jég-tűzkő', '5 db Nemere szarva', '3 db Pihe'] },
    ],
    location: 'Theowahdan',
    npcs: ['Theowahdan'],
    bonuses: ['Főszörnyek elleni erő +2%', 'Jég ereje +5%'],
    image: '/images/pets/fagyos-lehelet.png',
    wikiUrl: 'https://wiki.venor2.hu/items/210090',
  },
  {
    id: 'aprodka',
    name: 'Apródka',
    category: 'Pet kosztüm',
    rarity: 'common',
    sources: ['shop'],
    acquisition: [
      { kind: 'shop', text: 'Megvásárolható Theowahdan NPC-nél', costs: ['100 db Apród lélek'] },
    ],
    location: 'Theowahdan',
    npcs: ['Theowahdan'],
    bonuses: ['Szörnyek elleni erő +5%', 'Átlagos károk 3%'],
    image: '/images/pets/aprodka.png',
    wikiUrl: 'https://wiki.venor2.hu/items/210106',
  },
  {
    id: 'spidogi',
    name: 'Spidogi',
    category: 'Pet kosztüm',
    rarity: 'common',
    sources: ['boss', 'dungeon'],
    acquisition: [
      { kind: 'boss', text: 'Esik a(z) Pók-bárónő nevű bossból' },
      { kind: 'dungeon', text: 'Megszerezhető innen: Pók kazamata' },
    ],
    location: 'Pók-bárónő',
    bonuses: ['Szörnyek elleni erő +1%', 'Szél ereje +3%'],
    image: '/images/pets/spidogi.png',
    wikiUrl: 'https://wiki.venor2.hu/items/210112',
  },
  {
    id: 'mezi',
    name: 'Mézi',
    category: 'Pet kosztüm',
    rarity: 'common',
    sources: ['drop'],
    acquisition: [
      { kind: 'drop', text: 'Kinyerhető ebből a ládából: Kuldetesek láda' },
    ],
    bonuses: ['Szörnyek elleni erő +2%', 'Ördögök elleni erő +5%'],
    image: '/images/pets/mezi.png',
    wikiUrl: 'https://wiki.venor2.hu/items/210116',
  },
  {
    id: '107-es-ceh-topije',
    name: '107-es céh Töpije',
    category: 'Pet kosztüm',
    rarity: 'common',
    sources: ['shop'],
    acquisition: [
      { kind: 'shop', text: 'Megvásárolható Vegyeskereskedő Eladónő NPC-nél', costs: ['500 db Töpi lélek', '50 000 db Harmat láda'] },
    ],
    location: 'Vegyeskereskedő Eladónő',
    npcs: ['Vegyeskereskedő Eladónő'],
    bonuses: ['Dupla tárgy dobás esélye +1%', 'Szörnyek elleni erő +5%'],
    image: '/images/pets/107-es-ceh-topije.png',
    wikiUrl: 'https://wiki.venor2.hu/items/210121',
  },
  {
    id: 'vigyor-kandur',
    name: 'Vigyor Kandúr',
    category: 'Pet kosztüm',
    rarity: 'common',
    sources: [],
    bonuses: ['Szörnyek elleni erő +5%'],
    image: '/images/pets/vigyor-kandur.png',
    wikiUrl: 'https://wiki.venor2.hu/items/210132',
  },
  {
    id: 'groot',
    name: 'Groot',
    category: 'Pet kosztüm',
    rarity: 'common',
    sources: ['event', 'shop'],
    acquisition: [
      { kind: 'event', text: 'Elérhető ez alatt: Szél Element Event' },
      { kind: 'shop', text: 'Megvásárolható Elementális kereskedő (Szél) NPC-nél', costs: ['500 db Szél kristály', '1 db Szipi', '1 db Szellőke', '10 db Szél jegyzet'] },
      { kind: 'shop', text: 'Megvásárolható Elementális kereskedő (Villám) NPC-nél', costs: ['1 db Diana', '200 db Villám kristály'] },
    ],
    location: 'Elementális kereskedő (Szél)',
    npcs: ['Elementális kereskedő (Szél)', 'Elementális kereskedő (Villám)'],
    bonuses: ['Dupla tárgy dobás esélye +2%', 'Sungma Erő +2', 'Szél ereje +10%'],
    image: '/images/pets/groot.png',
    wikiUrl: 'https://wiki.venor2.hu/items/210139',
  },
  {
    id: 'leafy',
    name: 'Leafy',
    category: 'Pet kosztüm',
    rarity: 'common',
    sources: ['event', 'shop'],
    acquisition: [
      { kind: 'event', text: 'Elérhető ez alatt: Természet Haragja Event' },
      { kind: 'shop', text: 'Megvásárolható Természet hercegnője NPC-nél', costs: ['80 db Orgona', '40 db Alpesi rózsa', '5000 db Vörös ékszerdoboz', '5000 db Lila ékszerdoboz'] },
    ],
    location: 'Természet hercegnője',
    npcs: ['Természet hercegnője'],
    bonuses: ['Szörnyek elleni erő +3%', 'Mágikus/közelharci támadás +2%'],
    image: '/images/pets/leafy.png',
    wikiUrl: 'https://wiki.venor2.hu/items/210141',
  },
  {
    id: 'szipi',
    name: 'Szipi',
    category: 'Pet kosztüm',
    rarity: 'common',
    sources: ['event', 'shop'],
    acquisition: [
      { kind: 'event', text: 'Elérhető ez alatt: Szél Element Event' },
      { kind: 'shop', text: 'Megvásárolható Elementális kereskedő (Szél) NPC-nél', costs: ['200 db Szél kristály'] },
      { kind: 'shop', text: 'Megvásárolható Elementális kereskedő (Villám) NPC-nél', costs: ['1 db Kék Láng', '50 db Villám kristály'] },
    ],
    location: 'Elementális kereskedő (Szél)',
    npcs: ['Elementális kereskedő (Szél)', 'Elementális kereskedő (Villám)'],
    bonuses: ['Szörnyek elleni erő +4%'],
    image: '/images/pets/szipi.png',
    wikiUrl: 'https://wiki.venor2.hu/items/210142',
  },
  {
    id: 'mambo',
    name: 'Mambo',
    category: 'Pet kosztüm',
    rarity: 'common',
    sources: [],
    bonuses: ['Szörnyek elleni erő +3%', 'Dupla tárgy dobás esélye +3%'],
    image: '/images/pets/mambo.png',
    wikiUrl: 'https://wiki.venor2.hu/items/210143',
  },
  {
    id: 'taktik',
    name: 'TakTik',
    category: 'Pet kosztüm',
    rarity: 'common',
    sources: ['shop'],
    acquisition: [
      { kind: 'shop', text: 'Megvásárolható Theowahdan NPC-nél', costs: ['100 db Hasadék kő (IH)', '10 db TikTak', '100 db Szerpent lemez'] },
    ],
    location: 'Theowahdan',
    npcs: ['Theowahdan'],
    bonuses: ['Yohara főszörnyek elleni erő +1%', 'Yohara kövek elleni erő +1%', 'Szörnyek elleni erő +3%'],
    image: '/images/pets/taktik.png',
    wikiUrl: 'https://wiki.venor2.hu/items/210146',
  },
  {
    id: 'szelloke',
    name: 'Szellőke',
    category: 'Pet kosztüm',
    rarity: 'common',
    sources: ['drop', 'event', 'shop'],
    acquisition: [
      { kind: 'drop', text: 'Kinyerhető ebből a ládából: Szel láda' },
      { kind: 'event', text: 'Elérhető ez alatt: Szél Element Event' },
      { kind: 'shop', text: 'Megvásárolható Elementális kereskedő (Szél) NPC-nél', costs: ['100 db Szél láda'] },
      { kind: 'shop', text: 'Megvásárolható Elementális kereskedő (Villám) NPC-nél', costs: ['1 db Bambusz', '50 db Villám kristály'] },
    ],
    location: 'Elementális kereskedő (Szél)',
    npcs: ['Elementális kereskedő (Szél)', 'Elementális kereskedő (Villám)'],
    bonuses: ['Kövek elleni erő +2%', 'Átlagos károk 2%'],
    image: '/images/pets/szelloke.png',
    wikiUrl: 'https://wiki.venor2.hu/items/210147',
  },
  {
    id: 'diana',
    name: 'Diana',
    category: 'Pet kosztüm',
    rarity: 'common',
    sources: ['event', 'shop'],
    acquisition: [
      { kind: 'event', text: 'Elérhető ez alatt: Villám Element Event' },
      { kind: 'shop', text: 'Megvásárolható Elementális kereskedő (Villám) NPC-nél', costs: ['500 db Villám kristály', '1 db Kék Láng', '2 db Bambusz', '20 db Villám jegyzet'] },
    ],
    location: 'Elementális kereskedő (Villám)',
    npcs: ['Elementális kereskedő (Villám)'],
    bonuses: ['Dupla tárgy dobás esélye +1%', 'Yohara kövek elleni erő +2%', 'Villám ereje +10%'],
    image: '/images/pets/diana.png',
    wikiUrl: 'https://wiki.venor2.hu/items/210148',
  },
  {
    id: 'kek-lang',
    name: 'Kék Láng',
    category: 'Pet kosztüm',
    rarity: 'common',
    sources: ['event', 'shop'],
    acquisition: [
      { kind: 'event', text: 'Elérhető ez alatt: Villám Element Event' },
      { kind: 'shop', text: 'Megvásárolható Elementális kereskedő (Villám) NPC-nél', costs: ['300 db Villám kristály'] },
    ],
    location: 'Elementális kereskedő (Villám)',
    npcs: ['Elementális kereskedő (Villám)'],
    bonuses: ['Szörnyek elleni erő +3%'],
    image: '/images/pets/kek-lang.png',
    wikiUrl: 'https://wiki.venor2.hu/items/210164',
  },
  {
    id: 'skelejerry',
    name: 'SkeleJerry',
    category: 'Pet kosztüm',
    rarity: 'common',
    sources: ['shop'],
    acquisition: [
      { kind: 'shop', text: 'Megvásárolható Heti ranglista őre NPC-nél', costs: ['60 db Skele lélek'] },
    ],
    location: 'Heti ranglista őre',
    npcs: ['Heti ranglista őre'],
    bonuses: ['Dupla tárgy dobás esélye +1%', 'Yohara kövek elleni erő +5%', 'Kövek elleni erő +5%'],
    image: '/images/pets/skelejerry.png',
    wikiUrl: 'https://wiki.venor2.hu/items/210175',
  },
  {
    id: 'skeletom',
    name: 'SkeleTom',
    category: 'Pet kosztüm',
    rarity: 'common',
    sources: ['shop'],
    acquisition: [
      { kind: 'shop', text: 'Megvásárolható Heti ranglista őre NPC-nél', costs: ['20 db Skele lélek'] },
    ],
    location: 'Heti ranglista őre',
    npcs: ['Heti ranglista őre'],
    bonuses: ['Yohara főszörnyek elleni erő +3%', 'Főszörnyek elleni erő +3%'],
    image: '/images/pets/skeletom.png',
    wikiUrl: 'https://wiki.venor2.hu/items/210176',
  },
  {
    id: 'fenyek-orzoje',
    name: 'Fények Örzője',
    category: 'Pet kosztüm',
    rarity: 'common',
    sources: ['event'],
    acquisition: [
      { kind: 'event', text: 'Elérhető ez alatt: Kövek próbája Event' },
    ],
    bonuses: ['Sungma Erő +2', 'Max. TP +1500'],
    image: '/images/pets/fenyek-orzoje.png',
    wikiUrl: 'https://wiki.venor2.hu/items/210178',
  },
  {
    id: 'cerberus',
    name: 'Cerberus',
    category: 'Pet kosztüm',
    rarity: 'common',
    sources: ['shop'],
    acquisition: [
      { kind: 'shop', text: 'Megvásárolható Theowahdan NPC-nél', costs: ['500 db Cerberus lélek', '5000 db Nemes fa', '50 000 db Kő-töredék'] },
    ],
    location: 'Theowahdan',
    npcs: ['Theowahdan'],
    bonuses: ['Átlagos károk 2%', 'Varázssebesség +10%', 'Dupla tárgy dobás esélye +1%'],
    image: '/images/pets/cerberus.png',
    wikiUrl: 'https://wiki.venor2.hu/items/210180',
  },
  {
    id: 'bagi',
    name: 'Bagi',
    category: 'Pet kosztüm',
    rarity: 'common',
    sources: ['shop'],
    acquisition: [
      { kind: 'shop', text: 'Megvásárolható Chaegirab biológus NPC-nél', costs: ['200 db Biológus token', '50 db Kutatói elixír', '50 db Biológus Idő Eltávolító'] },
    ],
    location: 'Chaegirab biológus',
    npcs: ['Chaegirab biológus'],
    bonuses: ['Készség károk 3%', 'Szörnyek elleni erő +1%'],
    image: '/images/pets/bagi.png',
    wikiUrl: 'https://wiki.venor2.hu/items/210186',
  },
  {
    id: 'cerka',
    name: 'Cerka',
    category: 'Pet kosztüm',
    rarity: 'common',
    sources: ['shop'],
    acquisition: [
      { kind: 'shop', text: 'Megvásárolható Chaegirab biológus NPC-nél', costs: ['800 db Biológus token', '200 db Kutatói elixír', '200 db Biológus Idő Eltávolító'] },
    ],
    location: 'Chaegirab biológus',
    npcs: ['Chaegirab biológus'],
    bonuses: ['Készség károk 5%', 'Szörnyek elleni erő +2%'],
    image: '/images/pets/cerka.png',
    wikiUrl: 'https://wiki.venor2.hu/items/210187',
  },
  {
    id: 'kekike',
    name: 'Kékike',
    category: 'Pet kosztüm',
    rarity: 'common',
    sources: ['event', 'shop'],
    acquisition: [
      { kind: 'event', text: 'Elérhető ez alatt: Utó Nyári Event' },
      { kind: 'shop', text: 'Megvásárolható A nyár őre NPC-nél', costs: ['15 db Nyári lélek', '50 db Holdkő', '1000 db Magenta gyöngy'] },
    ],
    location: 'A nyár őre',
    npcs: ['A nyár őre'],
    bonuses: ['Yohara kövek elleni erő +1%', 'Szörnyek elleni erő +2%'],
    image: '/images/pets/kekike.png',
    wikiUrl: 'https://wiki.venor2.hu/items/210193',
  },
  {
    id: 'uszogumi',
    name: 'Úszógumi',
    category: 'Pet kosztüm',
    rarity: 'common',
    sources: ['event', 'shop'],
    acquisition: [
      { kind: 'event', text: 'Elérhető ez alatt: Holiday Event' },
      { kind: 'shop', text: 'Megvásárolható Afrodité NPC-nél', costs: ['200 db Dinnye lélek', '10 000 db Vörös ékszerdoboz', '10 000 db Lila ékszerdoboz', '300 db Csiszolt kő'] },
      { kind: 'shop', text: 'Megvásárolható A nyár őre NPC-nél', costs: ['1 db Zsugabuga', '15 db Nyári lélek', '5000 db Fagylaltgombóc'] },
    ],
    location: 'Afrodité',
    npcs: ['Afrodité', 'A nyár őre'],
    bonuses: ['Sungma Erő +1', 'Sungma VIT +1', 'Szörnyek elleni erő +3%'],
    image: '/images/pets/uszogumi.png',
    wikiUrl: 'https://wiki.venor2.hu/items/210194',
  },
  {
    id: 'zsugabuga',
    name: 'Zsugabuga',
    category: 'Pet kosztüm',
    rarity: 'common',
    sources: ['event', 'shop'],
    acquisition: [
      { kind: 'event', text: 'Elérhető ez alatt: Utó Nyári Event' },
      { kind: 'shop', text: 'Megvásárolható A nyár őre NPC-nél', costs: ['1 db Kékike', '100 db Nyári lélek', '500 db Csiszolt kő', '1000 db Misztikus töredék'] },
    ],
    location: 'A nyár őre',
    npcs: ['A nyár őre'],
    bonuses: ['Yohara kövek elleni erő +2%', 'Sungma Erő +1', 'Sungma VIT +1'],
    image: '/images/pets/zsugabuga.png',
    wikiUrl: 'https://wiki.venor2.hu/items/210199',
  },
  {
    id: 'a-fekete-gyongy',
    name: 'A fekete gyöngy',
    category: 'Pet kosztüm',
    rarity: 'common',
    sources: ['boss', 'dungeon'],
    acquisition: [
      { kind: 'boss', text: 'Esik a(z) Hidra kincse nevű bossból' },
      { kind: 'dungeon', text: 'Megszerezhető innen: Hidra támadása' },
    ],
    location: 'Hidra kincse',
    bonuses: ['Dupla tárgy dobás esélye +1%', 'Jég ereje +5%'],
    image: '/images/pets/a-fekete-gyongy.png',
    wikiUrl: 'https://wiki.venor2.hu/items/210207',
  },
  {
    id: 'kiraly-pingvin',
    name: 'Király pingvin',
    category: 'Pet kosztüm',
    rarity: 'common',
    sources: [],
    bonuses: ['Szörnyek elleni erő +3%', 'Esély kritikus találatra +10%', 'Dupla tárgy dobás esélye +1%'],
    image: '/images/pets/kiraly-pingvin.png',
    wikiUrl: 'https://wiki.venor2.hu/items/210226',
  },
  {
    id: 'luna',
    name: 'Luna',
    category: 'Pet kosztüm',
    rarity: 'common',
    sources: [],
    bonuses: ['Szörnyek elleni erő +3%', 'Főszörnyek elleni erő +3%'],
    image: '/images/pets/luna.png',
    wikiUrl: 'https://wiki.venor2.hu/items/210236',
  },
  {
    id: 'moki',
    name: 'Moki',
    category: 'Pet kosztüm',
    rarity: 'common',
    sources: ['shop'],
    acquisition: [
      { kind: 'shop', text: 'Megvásárolható Alkimista NPC-nél', costs: ['1000 db Cor Draconis (Nyers)', '200 db Zöld sárkány-bab'] },
    ],
    location: 'Alkimista',
    npcs: ['Alkimista'],
    bonuses: ['Átlagos károk 2%', 'Készség károk 2%'],
    image: '/images/pets/moki.png',
    wikiUrl: 'https://wiki.venor2.hu/items/210238',
  },
  {
    id: 'moka',
    name: 'Moka',
    category: 'Pet kosztüm',
    rarity: 'common',
    sources: ['shop'],
    acquisition: [
      { kind: 'shop', text: 'Megvásárolható Alkimista NPC-nél', costs: ['1000 db Cor Draconis (Legendás)', '5000 db Zöld sárkány-bab'] },
    ],
    location: 'Alkimista',
    npcs: ['Alkimista'],
    bonuses: ['Átlagos károk 3%', 'Készség károk 3%'],
    image: '/images/pets/moka.png',
    wikiUrl: 'https://wiki.venor2.hu/items/210239',
  },
  {
    id: 'villam',
    name: 'Villám',
    category: 'Pet kosztüm',
    rarity: 'common',
    sources: ['boss', 'dungeon'],
    acquisition: [
      { kind: 'boss', text: 'Esik a(z) Beran-Setaou nevű bossból' },
      { kind: 'dungeon', text: 'Megszerezhető innen: Sárkány templom' },
    ],
    location: 'Beran-Setaou',
    bonuses: ['Szörnyek elleni erő +1%', 'Villám ereje +3%'],
    image: '/images/pets/villam.png',
    wikiUrl: 'https://wiki.venor2.hu/items/210240',
  },
  {
    id: 'idorion',
    name: 'Idorion',
    category: 'Pet kosztüm',
    rarity: 'common',
    sources: ['event', 'shop'],
    acquisition: [
      { kind: 'event', text: 'Elérhető ez alatt: Időhasadék Kincsei Event' },
      { kind: 'shop', text: 'Megvásárolható Időhasadék kereskedő NPC-nél', costs: ['100 db Pegazus lélek', '10 db Titán-dioxid', '10 db Achát', '20 db Mithril'] },
    ],
    location: 'Időhasadék kereskedő',
    npcs: ['Időhasadék kereskedő'],
    bonuses: ['Szörnyek elleni erő +3%', 'Sungma VIT +1', 'Átlagos kár védelem 5%'],
    image: '/images/pets/idorion.png',
    wikiUrl: 'https://wiki.venor2.hu/items/210241',
  },
  {
    id: 'chiyan',
    name: 'Chiyan',
    category: 'Pet kosztüm',
    rarity: 'common',
    sources: ['shop'],
    acquisition: [
      { kind: 'shop', text: 'Megvásárolható Theowahdan NPC-nél', costs: ['300 db Elementális tekercs', '10 db Aura bónusz cserélő', '100 db Cor Draconis (Legendás)'] },
    ],
    location: 'Theowahdan',
    npcs: ['Theowahdan'],
    bonuses: ['Mágikus/közelharci támadás +2%', 'Max. TP +2500'],
    image: '/images/pets/chiyan.png',
    wikiUrl: 'https://wiki.venor2.hu/items/210242',
  },
  {
    id: 'lombo',
    name: 'Lombo',
    category: 'Pet kosztüm',
    rarity: 'common',
    sources: ['shop'],
    acquisition: [
      { kind: 'shop', text: 'Megvásárolható Theowahdan NPC-nél', costs: ['100 db Sárkány karom', '100 db Sárkány pikkely', '20 db Rituális kő', '3 db Villám'] },
    ],
    location: 'Theowahdan',
    npcs: ['Theowahdan'],
    bonuses: ['Szörnyek elleni erő +2%', 'Villám ereje +5%'],
    image: '/images/pets/lombo.png',
    wikiUrl: 'https://wiki.venor2.hu/items/210243',
  },
  {
    id: 'rak-ur',
    name: 'Rák Úr',
    category: 'Pet kosztüm',
    rarity: 'common',
    sources: ['boss', 'event'],
    acquisition: [
      { kind: 'boss', text: 'Esik a(z) Pénzes Rák nevű bossból' },
      { kind: 'event', text: 'Elérhető ez alatt: Pénztárca Event' },
    ],
    location: 'Pénzes Rák',
    bonuses: ['Szörnyek elleni erő +3%', 'Sungma Erő +2'],
    image: '/images/pets/rak-ur.png',
    wikiUrl: 'https://wiki.venor2.hu/items/210383',
  },
  {
    id: 'asmodeus-fonixe',
    name: 'Asmodeus főnixe',
    category: 'Pet kosztüm',
    rarity: 'common',
    sources: ['drop', 'event', 'shop'],
    acquisition: [
      { kind: 'drop', text: 'Kinyerhető ebből a ládából: Asmodeus láda' },
      { kind: 'event', text: 'Elérhető ez alatt: Asmodeus Event' },
      { kind: 'shop', text: 'Megvásárolható Asmodeus őre NPC-nél', costs: ['50 db Asmodeus ládája'] },
    ],
    location: 'Asmodeus őre',
    npcs: ['Asmodeus őre'],
    bonuses: ['Szörnyek elleni erő +3%', 'Kövek elleni erő +1%'],
    image: '/images/pets/asmodeus-fonixe.png',
    wikiUrl: 'https://wiki.venor2.hu/items/211101',
  },
  {
    id: 'megvaltas-fonixe',
    name: 'Megváltás főnixe',
    category: 'Pet kosztüm',
    rarity: 'common',
    sources: ['drop', 'event'],
    acquisition: [
      { kind: 'drop', text: 'Kinyerhető ebből a ládából: Asmodeus Zsakmany' },
      { kind: 'event', text: 'Elérhető ez alatt: Asmodeus Event' },
    ],
    bonuses: ['Szörnyek elleni erő +5%'],
    image: '/images/pets/megvaltas-fonixe.png',
    wikiUrl: 'https://wiki.venor2.hu/items/211102',
  },
  {
    id: 'tiktak',
    name: 'TikTak',
    category: 'Pet kosztüm',
    rarity: 'common',
    sources: ['drop', 'dungeon'],
    acquisition: [
      { kind: 'drop', text: 'Kinyerhető ebből a ládából: Idohasadek láda' },
      { kind: 'dungeon', text: 'Megszerezhető innen: IH Beran kazamata' },
      { kind: 'dungeon', text: 'Megszerezhető innen: IH Razador kazamata' },
      { kind: 'dungeon', text: 'Megszerezhető innen: IH Nemere kazamata' },
      { kind: 'dungeon', text: 'Megszerezhető innen: IH Jotun kazamata' },
    ],
    location: 'IH Beran kazamata',
    bonuses: ['Sungma Erő +2', 'Sungma VIT +2', 'Szörnyek elleni erő +3%'],
    image: '/images/pets/tiktak.png',
    wikiUrl: 'https://wiki.venor2.hu/items/211152',
  },
  {
    id: 'igli',
    name: 'Igli',
    category: 'Pet kosztüm',
    rarity: 'common',
    sources: ['event', 'shop'],
    acquisition: [
      { kind: 'event', text: 'Elérhető ez alatt: Időhasadék Kincsei Event' },
      { kind: 'shop', text: 'Megvásárolható Időhasadék kereskedő NPC-nél', costs: ['10 db Pegazus lélek', '2 db Titán-dioxid', '2 db Achát', '5 db Mithril'] },
    ],
    location: 'Időhasadék kereskedő',
    npcs: ['Időhasadék kereskedő'],
    bonuses: ['Sungma Erő +1', 'Szörnyek elleni erő +2%'],
    image: '/images/pets/igli.png',
    wikiUrl: 'https://wiki.venor2.hu/items/211168',
  },
  {
    id: 'kis-rak',
    name: 'Kis rák',
    category: 'Pet kosztüm',
    rarity: 'common',
    sources: ['event', 'shop'],
    acquisition: [
      { kind: 'event', text: 'Elérhető ez alatt: Holiday Event' },
      { kind: 'shop', text: 'Megvásárolható Afrodité NPC-nél', costs: ['20 db Dinnye lélek', '20 000 db Kő-töredék'] },
      { kind: 'shop', text: 'Megvásárolható A nyár őre NPC-nél', costs: ['1 db Kékike'] },
    ],
    location: 'Afrodité',
    npcs: ['Afrodité', 'A nyár őre'],
    bonuses: ['Szörnyek elleni erő +4%', 'Kövek elleni erő +2%'],
    image: '/images/pets/kis-rak.png',
    wikiUrl: 'https://wiki.venor2.hu/items/211169',
  },
  {
    id: 'voraki',
    name: 'Voraki',
    category: 'Pet kosztüm',
    rarity: 'common',
    sources: ['event', 'shop'],
    acquisition: [
      { kind: 'event', text: 'Elérhető ez alatt: Vorakel Kincsei Event' },
      { kind: 'shop', text: 'Megvásárolható Esemény segítő NPC-nél', costs: ['10 db Vorakel lélek', '20 db Turmalin töredék', '20 db Mithril'] },
    ],
    location: 'Esemény segítő',
    npcs: ['Esemény segítő'],
    bonuses: ['Főszörnyek elleni erő +2%', 'Kövek elleni erő +2%'],
    image: '/images/pets/voraki.png',
    wikiUrl: 'https://wiki.venor2.hu/items/211170',
  },
];
